picc_homepage:
    path:  /{id}
    defaults: { _controller: piccBundle:Default:index, id: 1 }
    requirements:
        id: \d+

picc_pages:
    path:  /page/{id}
    defaults: { _controller: piccBundle:Default:index, id: 1 }
    requirements:
        id: \d+

picc_view:
    path: /picc/{id}
    defaults: { _controller: piccBundle:Default:showPicc, id: 1 }
    requirements:
        id: \d+

